require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  NewCops: enable
  Exclude:
    - bin/**
    - vendor/**/*
    - db/schema.rb
    - config.ru
    - tmp/**/*
    - public/**/*

Style/Documentation:
  Enabled: false

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
