name: frontend-lint
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.17.0"
      - name: npm run lint
        working-directory: ${{ github.workspace }}/frontend
        run: "npm run lint"
